CREATE DATABASE IF NOT EXISTS nclouds_app;
USE nclouds_app;
CREATE TABLE IF NOT EXISTS users (
    id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    user VARCHAR(20) UNIQUE NOT NULL,
    password VARCHAR(32) NOT NULL
);